replicaCount: 1

image:
  repository: frontend
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  nodePort: 30001

ingress:
  enabled: false

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
