replicaCount: 1

image:
  repository: payments
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 5039
  nodePort: 30002

ingress:
  enabled: false

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
