apiVersion: v1
kind: Service
metadata:
  name: {{ include "frontend.fullname" . }}
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      nodePort: {{ .Values.service.nodePort | default nil }}
  selector:
    {{- include "frontend.selectorLabels" . | nindent 4 }}

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: debug-config
data:
  serviceType: "{{ .Values.service.type }}"
  servicePort: "{{ .Values.service.port }}"